### ISSUE TITLE
Visual Studio 2015 compiled failed in libtiff 4.0.6

### ISSUE THREAD

**Issue by henrya2** [bjornblissing/osg-3rdparty-cmake#28]
HAVE_SNPRINTF not set correctly cause compiling failed

libtiff 4.0.6

**Comment by henrya2** [comment]
Still failed

**Comment by bjornblissing** [comment]
Strange... Works on my machine. Could you post your build output?

**Comment by bjornblissing** [comment]
@henrya2 Just tried a both a 32-bit and 64-bit build on Visual Studio 2015 Community Edition with SP1 installed. Worked perfectly with libtiff 4.0.6.

**Comment by henrya2** [comment]
Sorry, I accidently roll back to libtiff 4.0.3 ...

**Comment by bjornblissing** [comment]
@henrya2 No problem. Good to hear that it is working!
