### ISSUE TITLE
Add support for CURL

### ISSUE THREAD

**Issue by bjornblissing** [bjornblissing/osg-3rdparty-cmake#4]
Add support for libcurl:

http://curl.haxx.se/

**Comment by bjornblissing** [comment]
Curl has basic support for CMake:
https://github.com/bagder/curl/

**Comment by robling** [comment]
I've find a script on github may help for building curl on windows. Here is the link : https://github.com/blackrosezy/build-libcurl-windows. Hope that helps.

**Comment by bjornblissing** [comment]
@robling Thank you, I will look into it.

**Comment by zakalawe** [comment]
Just to let you know I'm working on this is my local tree, I'm ignoring the Curl CMake support since it's marked as 'not well maintained'. I have something basic compiling but not sure which features are enabled / disabled yet. Didn't touch SSL at all so far.
