### ISSUE TITLE
How to build a glut dynamic library

### ISSUE THREAD

**Issue by skycuiok** [bjornblissing/osg-3rdparty-cmake#42]

**Comment by skycuiok** [comment]
I download the CMake scripts,then using CMake to create a static libray, I want to create dynamic libray,who can tell me how to do it?thanks.

**Comment by bjornblissing** [comment]
Added option to compile GLUT as a dynamic library. Note that this is advanced option in CMake (i.e. the option is hidden unless you check the *advanced" checkbox in the CMake GUI.)
